apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "blackbird.name" . }}-configmap
  labels:
    app: "{{ template "blackbird.name" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  blackbird.config: |-
    # Blackbird Bitcoin Arbitrage
    # Configuration file


    # Program parameters
    DemoMode=true
    Leg1=BTC
    Leg2=USD
    UseFullExposure=false
    TestedExposure=25.00
    MaxExposure=25000.00
    MaxLength=5184000
    DebugMaxIteration=3200000
    Verbose=true
    CACert=curl-ca-bundle.crt

    # Strategy parameters
    Interval=3.0
    SpreadEntry=0.0080
    SpreadTarget=0.0050
    PriceDeltaLimit=0.10
    TrailingSpreadLim=0.0008
    TrailingSpreadCount=1
    OrderBookFactor=3.0
    UseVolatility=false
    VolatilityPeriod=600

    # Email settings
    SendEmail=false
    SenderAddress=
    SenderUsername=
    SenderPassword=
    SmtpServerAddress=
    ReceiverAddress=

    # Database settings
    DBFile=blackbird.db

    # Bitfinex
    BitfinexApiKey=
    BitfinexSecretKey=
    BitfinexFees=0.0020
    BitfinexEnable=false

    # OkCoin
    OkCoinApiKey=d3b5374a-a8bc-4b9e-afbe-e82a4f4c8094
    OkCoinSecretKey=F4E606B7F00D1CE0E9284DB72F0C8C4C
    OkCoinFees=0.0020
    OkCoinEnable=true

    # Bitstamp
    BitstampClientId=
    BitstampApiKey=
    BitstampSecretKey=
    BitstampFees=0.0025
    BitstampEnable=false

    # Gemini
    GeminiApiKey=
    GeminiSecretKey=
    GeminiFees=0.0025
    GeminiEnable=false

    # Kraken
    KrakenApiKey=
    KrakenSecretKey=
    KrakenFees=0.0025
    KrakenEnable=false

    # ItBit
    ItBitApiKey=
    ItBitSecretKey=
    ItBitFees=0.0020
    ItBitEnable=false

    # WEX
    WEXApiKey=
    WEXSecretKey=
    WEXFees=0.0020
    WEXEnable=false

    # Poloniex
    # Note: no BTC/USD on Poloniex
    PoloniexApiKey=
    PoloniexSecretKey=
    PoloniexFees=0.0020
    PoloniexEnable=false

    # GDAX
    GDAXApiKey=
    GDAXSecretKey=
    GDAXPhrase=
    GDAXFees=0.0025
    GDAXEnable=false

    # QuadrigaCX
    QuadrigaApiKey=
    QuadrigaSecretKey=
    QuadrigaFees=0.005
    QuadrigaClientId=
    QuadrigaEnable=false

    # Exmo
    ExmoApiKey=
    ExmoSecretKey=
    ExmoFees=0.002
    ExmoEnable=false

    # Cex.io
    CexioClientId=up120105292
    CexioApiKey=USo5LPQBChLrESiSXXZ8r7nip68
    CexioSecretKey=ZpyECOOysNj7wHLOCEXFpScwYQ
    CexioFees=0.0025
    CexioEnable=true

    # Bittrex
    BittrexApiKey=
    BittrexSecretKey=
    BittrexFees=
    BittrexEnable=false

    # Binance
    BinanceApiKey=
    BinanceSecretKey=
    BinanceFees=
    BinanceEnable=false
